[package]
name = "config_validator"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1"
clap = { version = "4.5", features = ["derive"] }
